branch-defaults:
  master:
    environment: ARC-dev
global:
  application_name: ARC
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dev
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: ARC-0.0.1-SNAPSHOT.jar
