branch-defaults:
  master:
    environment: ARC-dev
    group_suffix: null
deploy:
  artifact: ARC/$CIRCLE_BUILD_NUM.jar
environment-defaults:
  ARC-dev:
    branch: null
    repository: null
global:
  application_name: ARC
  branch: null
  default_ec2_keyname: sample-key
  default_platform: Java 8
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dev
  repository: null
  sc: git
  workspace_type: Application
